In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5]) #리스트를 가지고 1차원 배열 생성
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
b = np.array([[10, 20, 30], [ 60, 70, 80]]) 
print(b) #출력
print(b.ndim) #차원 출력
print(b.shape) #크기 출력

[[10 20 30]
 [60 70 80]]
2
(2, 3)


ndarray의 초기화

In [4]:
a = np.zeros((2,3)) # 모든값이 0인 2x3 배열 생성.
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
a = np.ones((2,3)) # 모든값이 1인 2x3 배열 생성.
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
a = np.full((2,2), 7) # 모든 값이 특정 상수인 배열 생성. 이 경우에는 7.
print(a)

[[7 7]
 [7 7]]


In [7]:
a = np.eye(3) # 대각선으로는 1이고 나머지는 0인 2차원 배열을 생성.
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
a = np.random.random((2,2)) # 임의의 값으로 채워진 배열 생성
print(a)

[[0.78872371 0.75551212]
 [0.7019988  0.06273949]]


np.arange() # 지정해준 범위에 대해서 배열을 생성

In [11]:
a = np.arange(10) #0부터 9까지
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
a = np.arange(1, 10, 2) #1부터 9까지 +2씩 적용되는 범위
print(a)

[1 3 5 7 9]


reshape() # 배열을 다차원으로 변형

In [14]:
a = np.array(np.arange(30)).reshape((5,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


Numpy 슬라이싱 # 다차원 배열을 슬라이싱하기 위해서는 각 차원 별로 슬라이스 범위를 지정해줘야 함

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [16]:
b=a[0:2, 0:2]
print(b)

[[1 2]
 [4 5]]


In [17]:
b=a[0, :] # 첫번째 행 출력
print(b)

[1 2 3]


In [18]:
b=a[:, 1] # 두번째 열 출력
print(b)

[2 5]


Numpy 정수 인덱싱(integer indexing)

In [19]:
a = np.array([[1,2], [4,5], [7,8]])
b = a[[2, 1],[1, 0]] # a[[row2, row1],[col1, col0]]을 의미함.
print(b)

[8 4]


Numpy 연산

In [20]:
x = np.array([1,2,3])
y = np.array([4,5,6])
a = x + y # 각 요소에 대해서 더함
# a = np.add(x, y)와 동일함
print(a)

[5 7 9]


' - : np.subtract(x, y), * : np.multiply, / : np.divide

Numpy에서 벡터와 행렬의 곱 또는 행렬곱을 위해서는 dot()을 사용

In [21]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]
